### ISSUE TITLE
Error formatting - false positive

### ISSUE THREAD

**Issue by tomdavidson** [dprint/dprint-plugin-exec#23]
Version: 0.34.5

I'm running prettier-package-json with the exec plugin.  The associated files are formatted just fine but dprint exits with the error: 

> The original file text was greater than 100 characters, but the formatted text was empty. Perhaps dprint-plugin-exec has been misconfigured?

Entire config file attached, but heres exec:
```json
  "exec": {
    "associations": [
      "**/*.{sh,bash}",
      "**/package.json"
    ],
    "prettier-package-json.associations": "**/package.json",
    "prettier-package-json": "node_modules/.bin/prettier-package-json --write",
}
```

Got something wrong with the config or a bug?

[dprint.json.txt](https://github.com/dprint/dprint/files/10947639/dprint.json.txt)

**Comment by dsherret** [comment]
That’s to prevent you from accidentally overwriting all your files to empty files due to misconfiguration.

I’m just on my phone, but I think you need to set the stdin option to false. I don’t see a way to get that CLI to output its formatting to stdout (maybe there is a way and that’s preferred over this):

```json
"exec": {
    "associations": [
      "**/*.{sh,bash}",
      "**/package.json"
    ],
    "prettier-package-json.associations": "**/package.json",
    "prettier-package-json": "node_modules/.bin/prettier-package-json --write",
    "prettier-package-json.stdin": false
}
```

Side note: this config is too verbose. I opened https://github.com/dprint/dprint-plugin-exec/issues/24 now that it’s possible

**Comment by dsherret** [comment]
Oh wait, I think I did that wrong. I’ll go over to my computer

**Comment by dsherret** [comment]
Ok, this is what you're going to want to do:

```
"exec": {
    "associations": [
      "**/*.{sh,bash}",
      "**/package.json"
    ],
    "prettier-package-json.associations": "**/package.json",
    "prettier-package-json": "node_modules/.bin/prettier-package-json"
  },
```

I just tested it out and it works for me.

**Comment by tomdavidson** [comment]
Thanks for looking at this right away. With out the --write flag I experience some weirdness. So much so, that I did a screen grab. The workspace package.json gets replaced with the content of the root level package.json. Same when I turn off stdin.

![dprint-exec-prettier-packagejson-vodoo](https://user-images.githubusercontent.com/50412/224467508-42fb29bc-7418-417c-b83c-f6fb09bbef26.gif)

**Comment by tomdavidson** [comment]
If I use [pretty-package-json](https://www.npmjs.com/package/pretty-package-json) which supports stdin/out, things work as they should.

**Comment by dsherret** [comment]
Oh, I guess the plugin is not reading stdin. Providing the filepath seems to work and you can just ignore providing stdin since the plugin doesn't use it (I just checked its sourcecode):

```
"exec": {
    "associations": [
      "**/*.{sh,bash}",
      "**/package.json"
    ],
    "prettier-package-json.associations": "**/package.json",
    "prettier-package-json": "node_modules/.bin/prettier-package-json {{file_path}}",
    "prettier-package-json.stdin": false
  },
```

Sorry, getting the config setup sometimes can be tricky, but afterwards it's not so bad

**Comment by tomdavidson** [comment]
> Sorry, getting the config setup sometimes can be tricky, but afterwards it's not so bad

No complaints here. I love it. Just stumbled (forgot all about {{file_path}} and stdin: false) and thank you for your help!
