### ISSUE TITLE
does not work on nixos

### ISSUE THREAD

**Issue by paperdave** [dprint/dprint-plugin-exec#38]
dprint has been great for combining multiple formatters together, and i use the exec plugin to connect Zig to the mix in a personal project. however it seems the exec plugin breaks on NixOS, saying that a file is not found.

normally these mean something is up with unpatched binaries. though even with nix-ld, this issue seems to still happen. have yet to dig into the source code.

`dprint.jsonc`
```json
{
  "plugins": [
    "https://plugins.dprint.dev/exec-0.5.0.json@8d9972eee71fa1590e04873540421f3eda7674d0f1aae3d7c788615e7b7413d0",
  ],
  "excludes": [
    "**/.zig-cache",
    "**/zig-out",
  ],
  "exec": {
    "cwd": "${configDir}",
    "commands": [
      {
        "command": "zig fmt --stdin",
        "exts": ["zig", "zon"],
      },
    ],
  },
}
```

`hello.zig`
```zig
fn main() {}
```

`nix-shell -p dprint zig`

```
$ dprint fmt
Error formatting /home/dave/code/hello/hello.zig. Message: Cannot start formatter process: No such file or directory (os error 2)
Had 1 error formatting.
```

this error is not really useful. what file was not found? though i think posix spawn can return file not found without properly conveying what the file is.

**Comment by paperdave** [comment]
running strace, it seems that this is hit. is this an issue in dprint or the plugin? the config dir is never resolved. i can fix this by omitting the field

![image](https://github.com/user-attachments/assets/d4c40cd0-6a8f-4c59-b567-ab6ea08307aa)

**Comment by paperdave** [comment]
i believe i was simply out of date

**Comment by paperclover** [comment]
see above: install the latest version or remove the "${configDir}" param in cwd since it passed in without replacement in the old version.

in your ticket you are failing to even open it up. i recommend using nix-ld or another operating system so you can run the binaries out of the box. for example, i moved to macOS.
